# TAP_DANCE_ENABLE = yes
LTO_ENABLE = yes
UNICODE_COMMON = yes
CONSOLE_ENABLE = no
UNICODEMAP_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes


NKRO_ENABLE = yes
MUSIC_ENABLE = no
AUDIO_ENABLE = no
# do not work with the dead key and overrides/UM()
AUTO_SHIFT_ENABLE = yes
OS_DETECTION_ENABLE = yes
AUTOCORRECT_ENABLE = yes

SRC += daedric.c
